extensions: {}
cabal-file: project.cabal
version: 1
environment: ghc-7.4.2-stable-13.09
module-template: ! 'module MODULE_NAME where

'
ghc-args: []
modules:
  Main(src/Main.hs):
    filename: src/Main.hs
  Pipes:
    filename: src/Pipes.hs
  Conduit:
    filename: src/Conduit.hs
  Sisu:
    filename: src/Sisu.hs
  FiveParam:
    filename: src/FiveParam.hs
  Sisu2:
    filename: src/Sisu2.hs
  Data.Conduit3:
    filename: src/Data/Conduit3.hs
